### ISSUE TITLE
app.use() requires a middleware function

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/Web-Development-with-MongoDB-and-Node-Third-Edition#4]
I'm getting below error and its because of the code 'app.use(multer({ dest: path.join(__dirname, 'public/upload/temp')}));' in configure.js file. Appreciate your help.

D:\imgPloadr\node_modules\express\lib\application.js:210
    throw new TypeError('app.use() requires a middleware function')
    ^

TypeError: app.use() requires a middleware function
    at Function.use (D:\imgPloadr\node_modules\←[4mexpress←[24m\lib\applica
js:210:11)
    at module.exports (D:\imgPloadr\server\configure.js:33:6)
    at Object.<anonymous> (D:\imgPloadr\server.js:9:7)

**Comment by ghost** [comment]
Issue resolved: used code line as below:
app.use(multer({ dest: path.join(__dirname, 'public/upload/temp')}).any());

**Comment by ghost** [comment]
Now i'm getting below error when uploading file.

D:\imgPloadr\node_modules\mongodb\lib\utils.js:133
      throw err;
      ^

TypeError: Cannot read property 'path' of undefined
    at D:\imgPloadr\controllers\image.js:50:51
    at D:\imgPloadr\node_modules\←[4mmongoose←[24m\lib\model.js:4798:16

**Comment by bron10** [comment]
Please mention the chapter Number so that we may take a look and reply accordingly
